export const URLS = {
  // BASE_URL:'https://event-app-production-production.up.railway.app/',
  //BASE_URL:'https://cutz-production.up.railway.app/',
  //BASE_URL:'https://cutz-final-production.up.railway.app/',
  BASE_URL:'http://166.87.251.111:3006/',
  //BASE_URL:'http://192.168.68.61:3006/',
  //BASE_URL:'http://141.215.192.216:3006/',
  CLIENT_SIGNUP:'api/v1/client/signup',
  CLIENT_LOGIN:'api/v1/client/login',
  GET_CLIENT:'api/v1/client',
  CLIENT_FORGET_PASSWORD:'api/v1/forgetpasswordclient/resetpass',
  VOLUNTEER_FORGET_PASSWORD:'api/v1/forgetpasswordvolunteer/resetpass',
  VOLUNTEER_LOGIN:"api/v1/volunteer/login",
  VOLUNTEER_SIGNUP:"api/v1/volunteer/signup",
  CHECK_VOLUNTEER_EMAIL:'api/v1/forgetpasswordvolunteer/sendotp',
  CHECK_CLIENT_EMAIL:'api/v1/forgetpasswordclient/sendotp',
  VOLUNTEER_OTP_VERIFIED:'api/v1/forgetpasswordvolunteer/verifyotp',
  CLIENT_OTP_VERIFIED:'api/v1/forgetpasswordclient/verifyotp',
  GET_VOLUNTEER:'api/v1/volunteer',
  GET_EVENTS:'api/v1/event',
  EVENTS_RESERVATION_CLIENT:'api/v1/eventreservationclient',
  EVENTS_RESERVATION_VOLUNTEER:'api/v1/eventreservationvolunteer',
  EVENT_GROUP:"api/v1/eventgroup",
  UPLOAD_IMAGE:"api/v1/upload",
  ORGANIZATION:"api/v1/organization",
  TIMING:"api/v1/timing",
  GOOGL_MAP_API:"AIzaSyCpr_ajK9YsgNa184_UyE0e3BXmiPPXFZ8",
}