export const Urls = {
  // https://event-app-production-production.up.railway.app/api/v1/client/getall
  // BaseUrl:"https://cutz-production.up.railway.app/",
  //BaseUrl: "http://localhost:3006/",
  BaseUrl: "https://your-heroku-app.herokuapp.com/",

  //BaseUrl:'https://cutz-final-production.up.railway.app/',
  // BaseUrl:"https://event-app-production-production.up.railway.app/",
  CLIENT_SIGNUP: "api/v1/client/signup",
  CLIENT_LOGIN: "api/v1/client/login",
  GET_CLIENT: "api/v1/client",
  GET_CLIENT_ALL: "api/v1/client/getall",
  GET_ADMIN_ALL: "api/v1/admin/getall",
  ADMIN: "api/v1/admin",
  CLIENT_FORGET_PASSWORD: "api/v1/forgetpasswordclient/resetpass",
  VOLUNTEER_FORGET_PASSWORD: "api/v1/forgetpasswordvolunteer/resetpass",
  GET_VOLUNTEER_ALL: "api/v1/volunteer/getall",
  VOLUNTEER_LOGIN: "api/v1/volunteer/login",
  VOLUNTEER_SIGNUP: "api/v1/volunteer/signup",
  CHECK_VOLUNTEER_EMAIL: "api/v1/forgetpasswordvolunteer/sendotp",
  CHECK_CLIENT_EMAIL: "api/v1/forgetpasswordclient/sendotp",
  VOLUNTEER_OTP_VERIFIED: "api/v1/forgetpasswordvolunteer/verifyotp",
  CLIENT_OTP_VERIFIED: "api/v1/forgetpasswordclient/verifyotp",
  GET_VOLUNTEER: "api/v1/volunteer",
  GET_EVENTS: "api/v1/event",
  EVENTS_RESERVATION_CLIENT: "api/v1/eventreservationclient",
  EVENTS_RESERVATION_VOLUNTEER: "api/v1/eventreservationvolunteer",
  EVENT_GROUP: "api/v1/eventgroup",
  UPLOAD_IMAGE: "api/v1/upload",
  ORGANIZATION: "api/v1/organization",
  ORGANIZATION_ADMIN: "api/v1/organization/admin",
  TIMING: "api/v1/timing",
  DESCRIPTION: "api/v1/description",
  NOTIFICATION_FIELDS: "api/v1/notification/fields",
  NOTIFICATION: "api/v1/notification",
};
